name: my_to_do
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  splash:
    path: modules/splash
  task:
    path: modules/task
  
  lib_core:
    path: packages/lib_core
  lib_dependencies:
    path: packages/lib_dependencies
  lib_ds:
    path: packages/lib_ds

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
